const personDataObj = {
    unknown: {isUnknown: false, unknownData: ''},
    enslaved: {isEnslaved: false, value: ''},
    infant: {isInfant: false},
    lastBirthName: { value: '', isPreferred: false, isHidden: false },
    lastPenName: { value: '', isPreferred: false, isHidden: false },
    lastAnglicizedName: { value: '', isPreferred: false, isHidden: false },
    firstBirthName: { value: '', isPreferred: false, isHidden: false },
    shortenedName: { value: '', isPreferred: false, isHidden: false },
    firstInitial: { value: '', isPreferred: false, isHidden: false },
    firstPenName: { value: '', isPreferred: false, isHidden: false },
    firstAnglicizedName: { value: '', isPreferred: false, isHidden: false },
    nickname: { value: '', isPreferred: false, isHidden: false },
    middleBirthName: { value: '', isPreferred: false, isHidden: false },
    middleInitial: { value: '', isPreferred: false, isHidden: false },
    middleAnglicizedName: { value: '', isPreferred: false, isHidden: false },
    maidenName: { value: '', isPreferred: false, isHidden: false },
    additionalLastNames: { value: '', isPreferred: false, isHidden: false },
    nameSuffix: { value: '', isPreferred: false, isHidden: false },
    titleName: { value: '', isPreferred: false, isHidden: false },
    indigenousName: { value: '', isPreferred: false, isHidden: false },
    birthDate: { value: '', isCirca: false, beforeOrAfter: '' },
    deathDate: { value: '', isCirca: false, beforeOrAfter: '' },
    flourished: { value: '', isCirca: false, beforeOrAfter: '' }
}