let personDataObj = {
    nonHuman: {isNonHuman: false, value: '', resultStr: ''},
    unknown: {isUnknown: false, unknownData: '', resultStr: ''},
    lastBirthName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    lastPenName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    lastAnglicizedName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    infant: {isInfant: false, resultStr: ''},
    firstBirthName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    shortenedName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    firstInitial: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    firstPenName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    firstAnglicizedName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    nickname: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    middleBirthName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    middleInitial: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    middleAnglicizedName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    maidenName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    additionalLastNames: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    nameSuffix: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    titleName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    indigenousName: { value: '', isPreferred: false, isHidden: false , resultStr: ''},
    birthDate: { value: '', isCirca: false, beforeOrAfter: '' , resultStr: ''},
    deathDate: { isAlive: false, value: '', isCirca: false, beforeOrAfter: '' , resultStr: ''},
    flourished: { value: '', isCirca: false, beforeOrAfter: '' , resultStr: ''},
    enslaved: {isEnslaved: false, value: '', resultStr: ''},
    ficticious: {isFicticious: false, value: '', resultStr: ''},
}